### PR TITLE
Fix keyboard navigation of contacts

### LINKED ISSUE #221: Allow user to use up and down arrows to navigate better when searching for the name of an existing contact

### PR DESCRIPTION
**Pull request by schancel**
A previous commit enabled the contact search dialog to be opened with
Cmd-K. However, there were some oddities in the behavior when pressing
enter, or having accidentally had an address which was not part of the
search results. This commit removes some complexity, and adds the
necessary watchers to make sure that the address is always defined.

Fixes #221, #225, #287

### CODE REVIEW

File: src/components/contacts/ContactList.vue [hunk 1]
```diff
@@ -26,7 +26,7 @@ export default {
   props: ['contacts', 'contactClick'],
   data () {
     return {
-      activeAddress: Object.keys(this.contacts)[0]
```
Comment (schancel) [inline src/components/contacts/ContactList.vue:29]: This shouldn't be here.
